name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build Next.js
        run: npm run build

      - name: Copy out to root
        run: |
          rm -rf ./* # Remove all current files in the root.
          shopt -s dotglob # allows the copying of hidden files.
          cp -r out/* ./ # copy the out folder contents to the root.
          shopt -u dotglob # disables the dotglob option.
          touch .nojekyll # create the .nojekyll file.

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2 #or v3 depending on what you wish to use.